# Generated by Django 5.1.3 on 2025-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_generatedquestion_generatedanswer_generatedquiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedtopic',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
