# Generated by Django 5.1.3 on 2025-09-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_generatedtopic_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_topics', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='content.generatedtopic')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='content.generatedcourse')),
                ('last_accessed_topic', models.ForeignKey(help_text='The last topic the user viewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.generatedtopic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_course_progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
