# Generated by Django 5.1.3 on 2025-09-15 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_completedtopic_generatedcourseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedcourseprogress',
            options={'verbose_name_plural': 'Generated Course Progresses'},
        ),
        migrations.AlterField(
            model_name='generatedcourseprogress',
            name='last_accessed_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.generatedtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedcourseprogress',
            unique_together={('student', 'course')},
        ),
        migrations.CreateModel(
            name='GeneratedTopicCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.generatedtopic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
