# Generated by Django 5.1.3 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_generatedcourseprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopiccompletion',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
