# Generated by Django 5.1.3 on 2025-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_generatedtopiccompletion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanswer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
