# Generated by Django 5.1.3 on 2025-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_generatedanswer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopiccompletion',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
