# Generated by Django 5.1.3 on 2025-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_generatedtopiccompletion_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CppLearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('tutorial', 'Interactive Tutorial'), ('exercise', 'Practice Exercises'), ('documentation', 'Official Documentation')], max_length=20)),
                ('topic_category', models.CharField(choices=[('syntax', 'Syntax Basics'), ('oop', 'Object-Oriented Programming'), ('stl', 'STL & Templates'), ('memory', 'Memory Management'), ('advanced', 'Advanced Concepts')], max_length=20)),
                ('difficulty', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='generatedtopic',
            name='alternative_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedtopic',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
    ]
