# Generated by Django 5.1.3 on 2025-09-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_cpplearningresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopic',
            name='is_regenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedtopic',
            name='original_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerated_versions', to='content.generatedtopic'),
        ),
    ]
