# Generated by Django 5.1.3 on 2025-09-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_generatedtopic_is_regenerated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopiccompletion',
            name='wrong_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
