# Generated by Django 5.1.3 on 2025-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_generatedtopiccompletion_wrong_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopiccompletion',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
