# Generated by Django 5.1.3 on 2025-09-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_generatedtopiccompletion_attempt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopic',
            name='is_reinforcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedtopic',
            name='reinforcement_for_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinforcement_topics', to='content.generatedchapter'),
        ),
    ]
