# Generated by Django 5.1.3 on 2025-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_generatedtopic_is_reinforcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcourse',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='generatedcourse',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('moderate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=10),
        ),
    ]
