# Generated by Django 5.1.3 on 2025-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_generatedcourse_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcourse',
            name='chapters_count',
            field=models.IntegerField(default=0),
        ),
    ]
