# Generated by Django 5.1.3 on 2025-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_generatedcourse_chapters_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcourse',
            name='generated_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
