# Generated by Django 5.1.3 on 2025-09-18 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_generatedcourse_generated_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedcourse',
            unique_together={('user', 'title')},
        ),
    ]
