# Generated by Django 5.1.3 on 2025-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_generatedcourse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopic',
            name='is_generated',
            field=models.BooleanField(default=True),
        ),
    ]
