# Generated by Django 5.1.3 on 2025-09-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_generatedtopic_is_generated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedcourse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='generatedtopic',
            name='is_generated',
        ),
    ]
