# Generated by Django 5.1.3 on 2025-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_generatedcourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtopic',
            name='is_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generatedchapter',
            name='duration',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='generatedchapter',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedcourse',
            name='category',
            field=models.CharField(default='C++ Programming', max_length=100),
        ),
        migrations.DeleteModel(
            name='CompletedTopic',
        ),
    ]
